### ISSUE TITLE
Reduce image sizes

### ISSUE THREAD

**Issue by tianyikillua** [tianyikillua/code_aster_on_docker#2]
Currently the image size of `quay.io/tianyikillua/code_aster` is extremely large (4.5 GB), compared for instance to other general purpose FEA softwares for example FEniCS (1.8 GB)

According to this [page](https://stackoverflow.com/questions/24394243/why-are-docker-container-images-so-large), a cleanup should be performed after each `RUN`. This means the downloaded `tar`'s and extracted source files are not actually deleted, even though I did a `rm -rf` at the end of the `Dockerfile`.

**Comment by tianyikillua** [comment]
The size has been reduced to 2.9 GB, via https://github.com/tianyikillua/code_aster_on_docker/commit/a814aeca27eb233b44c8bdfbbe4f73788a6e56ad.

**Comment by Jesusbill** [comment]
Great!
