### ISSUE TITLE
Issue with initialization 

### ISSUE THREAD

**Issue by Paulsitobonito123** [tianyikillua/code_aster_on_docker#5]
Hi, at first let me thank you for the amazing you that you have done, it saves me a lot of time and troubles. I have always run code_aster inside the docker that you provide, mostly because the benefits of parallel compilation that your docker offers. But recently I havent been able to open the docker, I use the next command 

sudo docker run --cpuset-cpus="0-39" -ti --rm -v $(pwd):/home/aster/shared quay.io/tianyikillua/code_aster

But the next error pops up

docker: invalid reference format.
See 'docker run --help'.

I have review the documentation that you posted and found no solution.

What can I do to solve this problem? Is there any change in the structure of the docker or maybe it is in maintenance? 

Thank you in advance and best regards!.

**Comment by tianyikillua** [comment]
It seems to me a Docker problem. It works fine for me.

**Comment by tianyikillua** [comment]
@Paulsitobonito123 See https://stackoverflow.com/questions/45682010/docker-invalid-reference-format

**Comment by tianyikillua** [comment]
Feel free to reopen the issue. For me it's not related to this image.
